modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/TheCBProject/ChickenChunks"
license="The MIT License (MIT)"

[[mods]]
	modId="chickenchunks"
	displayName="ChickenChunks"
	version="${file.jarVersion}"

	updateJSONURL="https://version-check.covers1624.net/check/?mod=ChickenChunks&mc=${mc_version}"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/chicken-chunks-1-8"
	authors="ChickenBones, covers1624"
	description="Advanced ChunkLoading management"
[[dependencies.chickenchunks]]
	modId="neoforge"
    type="required"
	versionRange="[${forge_version},)"
	ordering="NONE"
	side="BOTH"
[[dependencies.chickenchunks]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.chickenchunks]]
    modId="codechickenlib"
    type="required"
    versionRange="${ccl_version_range}"
    ordering="NONE"
    side="BOTH"
